#!/bin/bash

SLEEP_TIME=60
ERR_LOG=~/.wallpaper/err
WALLPAPER_DIR=~/.wallpaper/wallpapers

FILES=(`find $WALLPAPER_DIR -regextype posix-extended -regex '.*(jpg|png)'|tr '\n' ' '`)
N_FILES=${#FILES[*]}

I=0

while true
do
  feh --bg-fill "${FILES[$I]}" 2> $ERR_LOG
  sleep $SLEEP_TIME

  if [ "$I" -lt "$N_FILES" ]; then
    I=$((I+1))
  else
    I=0
  fi
done
